### ISSUE TITLE
[Feature Request] Python SDK

### ISSUE THREAD

**Issue by WayneAl** [pontem-network/liquidswap-sdk#15]
Let's make the python-sdk for liquid swap.

I have done some example here.

[https://github.com/WayneAl/liquidswap-sdk/tree/python-sdk/python_sdk](https://github.com/WayneAl/liquidswap-sdk/tree/python-sdk/python_sdk)

**Comment by borispovod** [comment]
Hey @WayneAl ,

Thank you for your work. We currently updating the current Typescript SDK and going to do release this week.
I like your work and if you can make us python sdk with at least support of uncorrelated pools and swap functions i think we will be able to pay bounty for it.

**Comment by WayneAl** [comment]
I created another repo for only [python sdk](https://github.com/WayneAl/liquidswap-sdk-python)

WIP:
- [x] convertToDecimals
- [ ] calculateRates
- [ ] createSwapTransactionPayload
- [ ] create pypl package

**Comment by WayneAl** [comment]
Finished! plz check @borispovod 

here is the repo,
https://github.com/WayneAl/liquidswap-sdk-python

**Comment by WayneAl** [comment]
How’s the review going? Anything needs change?
