### ISSUE TITLE
How to calculate the x and y output amount according to the LP balance when redeeming liquidity?

### ISSUE THREAD

**Issue by y0unghe** [pontem-network/liquidswap-sdk#18]
Can you add a function to return the x and y output amount according to the LP balance when redeeming liquidity like `calculateRates` when swap?

**Comment by borispovod** [comment]
Hey, thank you, we currently updating SDK and expecting to do new release this week, so stay tuned.

We will add culculate rates in the current release or release after.

**Comment by lusd** [comment]
Hey! We are recently updated SDK with calculateRates for swap. stable version is 0.4.0 or higher.
We are planning ti add redeem liquidity flow in next releases.

**Comment by sirWill** [comment]
Functions to work with liquidity and calculations corresponding with it was added from 0.5.0 version.
