### ISSUE TITLE
[Feature Request] Missing functions

### ISSUE THREAD

**Issue by borispovod** [pontem-network/liquidswap-sdk#6]
We have to implement the following funcs:

* Create Pool.
* Remove liquidity.
* Add liquidity.
* Quotes before add liquidity or burn liquidity.
* Check if pool ever exists.

**Comment by y0unghe** [comment]
Do you have any idea how to make the register pool work? I tried blow but it failed with error: "Execution failed in 0xa277f7024ded2cd788072f035beaec108a01f7f305b1868c5d34a64da228662d::liquidity_pool::register at code offset 19"

`const rawTxn = await client.generateTransaction(aliceAccount.address(), {
        function: `0xa277f7024ded2cd788072f035beaec108a01f7f305b1868c5d34a64da228662d::scripts_v2::register_pool`,
        type_arguments: [
            "0xa277f7024ded2cd788072f035beaec108a01f7f305b1868c5d34a64da228662d::doge_coin::DogeCoin",
            "0x1::aptos_coin::AptosCoin",
            "0xa277f7024ded2cd788072f035beaec108a01f7f305b1868c5d34a64da228662d::curves::Uncorrelated"
        ],
        arguments: []
    });

    const bcsTxn = await client.signTransaction(aliceAccount, rawTxn);
    const pendingTxn = await client.submitTransaction(bcsTxn);

    console.log(pendingTxn);`
